### PR TITLE
Update tt-rss submodule to most recent version, light edits to README

### PR DESCRIPTION
**Pull request by harpojaeger**
Thanks for putting together this excellent package of scripts! I'm a longtime tt-rss user and was glad to get it running on Heroku so easily.

I updated the tt-rss submodule to the most recent version, and changed its repo URL to match the new one at tt-rss.org. I also made some light edits to `README.md` for clarity.

I got partway through the process of enhancing `app.json` to enable a Deploy to Heroku button, but it turns out those [don't support git submodules](https://devcenter.heroku.com/articles/heroku-button#requirements) (unless you use a custom buildpack, and even then there are authentication issues), so I added a note to `README.md` to clarify that.

### CODE REVIEW

**Comment by serl** [comment]
Hey thanks! :smile: 

Just to be sure, before I merge: I added a `LICENSE` file to the project, that was missing. It's a plain GPL3, as tt-rss. Is that ok for you?

**Comment by harpojaeger** [comment]
Sure, that works for me. I merged your changes in to my fork & updated the PR just to be extra-sure we're doing the license stuff right, and I also added `.DS_Store` to `.gitignore` for the Mac devs among us.

**Comment by serl** [comment]
Yup! Merged!

(actually, for Mac friends, there's the global gitignore...)

**Comment by harpojaeger** [comment]
Good stuff! I have some ideas about workarounds we might try to enable the Deploy to Heroku button. If you're interested, I could create an issue for that to spec it out and keep track of any ideas I come up with. Thoughts?

**Comment by serl** [comment]
I think you're morally obliged by now! :drum: :grinning:

**Comment by harpojaeger** [comment]
Great, will do later today.

**Pull request merged**
